### ISSUE TITLE
Implement a standard way to expose current application version

### ISSUE THREAD

**Issue by remiprev** [mirego/ember-boilerplate#10]
Like [we do](https://github.com/mirego/elixir-boilerplate/blob/80c3f5d463a70afe6118f5cfaeab9ec9b2463833/lib/elixir_boilerplate_web/health/plug.ex#L9) in Elixir Boilerplate, we should always be able to expose the currently deployed version.

Could we simply just add a standard `/health` endpoint and expose it there?

**Comment by charlesdemers** [comment]
We just need to expose the version, the endpoint already exists! 💥 https://github.com/mirego/ember-boilerplate/blob/master/node-server/server.js#L45
